"""
http://projecteuler.net/index.php?section=problems&id=2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fibs() :
    a, b = 1, 0
    while True :        
        yield a
        a, b = a+b, a

from itertools import takewhile

s = sum( i for i in takewhile( lambda i : i < 4*10**6, fibs() ) if i%2 == 0 )

assert s == 4613732
